spring:
  r2dbc:
    url: ${DB_R2DBC_URL:r2dbc:postgresql://localhost:5432/coursesdb}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:}
    pool:
      enabled: true
      initial-size: 30
      max-size: 30
server:
  port: 8080
